export const GET_PRODUCTS = 'GET_PRODUCTS_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const ADD_USER= 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
